### PR TITLE
Update to Julia 1.7.2 and update dependencies

### PR DESCRIPTION
**Pull request by jamesmurdza**
I have updated to Julia 1.7.2, updated dependencies, and fixed some small errors related to updating Ipopt.

It appears to work fine now, however I have one issue (#44) which I can’t tell is related to these changes or not. 

If it helps for testing, there is also a Docker file here: https://github.com/possibleplanets/DICE.jl-notebooks/blob/master/Dockerfile

### CODE REVIEW

**Comment by Libbum** [comment]
@jamesmurdza, I found the issue in #44, can you click the "Allow edits from maintainers" button so I can push a fix?

here

**Comment by jamesmurdza** [comment]
@Libbum Great!

Oddly I can't (https://github.com/isaacs/github/issues/1681). I can only add you to my fork.

**Comment by Libbum** [comment]
Oh! Wasn't aware of that limitation sorry.

Give those changes a shot and see if they work for you?

If so we can merge this and I'll release a new version.

**Comment by jamesmurdza** [comment]
Works great on my setup!

**Pull request merged**
